### ISSUE TITLE
每次都是调用服务取号吗?有没有每次取一段号放在本地，用完后再去远程去?

### ISSUE THREAD

**Issue by nsspw** [zhuzhong/idleaf#2]
如题

**Comment by zhuzhong** [comment]
现在没有，因为远程服务是从数据库每次取一段的，而业务使用方则没有取一段的，而是每次使用的时候，就调用服务。如果你的业务对于这个取号依赖很强，你可以考虑将这个功能直接集成到你的业务代码中，从而就不存在远程rpc这个调用性能消耗。
